name: Build and Push Airflow DAG Image

on:
  push:
    branches:
      - main
    paths:
      - "dags/**"
      - "requirements.txt"
      - "Dockerfile"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/sserkanguzel/project-1-1-batch-processing-airflow
      GITOPS_REPO: Project-1-Batch-Processing-Infrastructure
      GITOPS_PATH: airflow-manifests/values.yaml

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout DAG repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get date tag
        id: tag
        run: echo "date_tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.date_tag }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: sserkanguzel/airflow-deployment
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gitops

      - name: Update values.yaml with new image tag
        run: |
          sed -i "s|\(workerContainerImage:.*:\).*|\1${{ steps.tag.outputs.date_tag }}|" gitops/${{ env.GITOPS_PATH }}

      - name: Commit and push updated values.yaml
        run: |
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ${{ env.GITOPS_PATH }}
          git commit -m "Update image tag to ${{ steps.tag.outputs.date_tag }}"
          git push
