name: Build and Deploy Airflow DAG Image

permissions:
  contents: write
  packages: write
  
on:
  push:
    branches: [main]
    paths:
      - 'dags/**'
      - 'requirements.txt'
      - 'Dockerfile'

jobs:
  build-and-update:
    name: Build Docker image and update Helm values and pod_template.yaml
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ghcr.io/sserkanguzel/project-1-1-batch-processing-airflow

    steps:
      - name: Checkout DAG repo
        uses: actions/checkout@v4

      - name: Set datetime tag
        id: vars
        run: echo "tag=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.vars.outputs.tag }} .
          docker push $IMAGE_NAME:${{ steps.vars.outputs.tag }}

      - name: Clone Airflow deployment repo (GitOps)
        run: |
          git clone https://github.com/sserkanguzel/Project-1-Batch-Processing-Infrastructure.git infra

      - name: Configure Git
        run: |
          cd infra
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update image tag in values.yaml and pod_template.yaml
        run: |
          # Update image tag in Helm values.yaml
          sed -i "s|tag: .*|tag: '${{ steps.vars.outputs.tag }}'|" infra/airflow-manifests/values.yaml

          # Update container image in pod_template.yaml
          sed -i "s|image: .*|image: \"${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}\"|" infra/airflow-manifests/config/pod_template.yaml

      - name: Commit and push changes to deployment repo
        run: |
          cd infra
          git add airflow-manifests/values.yaml airflow-manifests/config/pod_template.yaml
          git commit -m "Update Airflow image tag to ${{ steps.vars.outputs.tag }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sserkanguzel/Project-1-Batch-Processing-Infrastructure.git HEAD:main
